<div class="breadcrumb">
	<span><?php echo $this->translate('Du bist hier:'); ?></span>
	<span class="breadcrumb">
	    <?php
	    // iterate through the pages
	    foreach ($this->pages as $key => $page):
	        ?>
	        <span>
	            <?php
	            // if this isn't the last page, add a link and the separator
	            if ($key < count($this->pages) - 1):
	                ?>
	                <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
	                <span class="separator">/</span>
	            <?php
	            // otherwise, just output the name
	            else:
	            ?>
	                <?php echo $page->getLabel(); ?>
	            <?php endif; ?>
	        </span>
	    <?php endforeach; ?>
	</span>
</div>