<div class="nav-breadcrumb">
	<ol class="breadcrumb">
		<li class="header"><?php echo $this->translate('Du bist hier :'); ?></li>
		<?php foreach ($this->pages as $key => $page): ?>
		<?php if ($key < count($this->pages) - 1): ?>
		<li>
			<a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
			<span class="separator hide">/</span>
		</li>
		<?php else: ?>
		<li class="active">
			<?php echo $page->getLabel(); ?>
		</li>
		<?php endif; ?>
		<?php endforeach; ?>
	</ol>
</div>